// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGokRdtf-MaPw0hqYiRpwWXaC4Sbulirw',
    appId: '1:231408503047:web:79f060b30c1aac58205da2',
    messagingSenderId: '231408503047',
    projectId: 'ofertix-435a6',
    authDomain: 'ofertix-435a6.firebaseapp.com',
    databaseURL: 'https://ofertix-435a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ofertix-435a6.firebasestorage.app',
    measurementId: 'G-8LD077RVF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuw8E5KmjP8UTFpRyT5wVqCwuwTlkms0',
    appId: '1:231408503047:android:0a1368845d41eca6205da2',
    messagingSenderId: '231408503047',
    projectId: 'ofertix-435a6',
    databaseURL: 'https://ofertix-435a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ofertix-435a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uLgXjEvdxtaqIr-bqC3n0bvJHG2XlMY',
    appId: '1:231408503047:ios:bc0bdaebbce483ab205da2',
    messagingSenderId: '231408503047',
    projectId: 'ofertix-435a6',
    databaseURL: 'https://ofertix-435a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ofertix-435a6.firebasestorage.app',
    iosBundleId: 'com.example.ofertix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2uLgXjEvdxtaqIr-bqC3n0bvJHG2XlMY',
    appId: '1:231408503047:ios:bc0bdaebbce483ab205da2',
    messagingSenderId: '231408503047',
    projectId: 'ofertix-435a6',
    databaseURL: 'https://ofertix-435a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ofertix-435a6.firebasestorage.app',
    iosBundleId: 'com.example.ofertix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGokRdtf-MaPw0hqYiRpwWXaC4Sbulirw',
    appId: '1:231408503047:web:efe4901d369c7bc8205da2',
    messagingSenderId: '231408503047',
    projectId: 'ofertix-435a6',
    authDomain: 'ofertix-435a6.firebaseapp.com',
    databaseURL: 'https://ofertix-435a6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ofertix-435a6.firebasestorage.app',
    measurementId: 'G-GT194XLDXZ',
  );
}
